### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by spacekookie** [spacekookie/barrel#1]
The big question is: does it make sense? Is it easy enough to use, without hiding any features away?

This issue will remain pinned during the `0.x` version period to provide discussion on how the barrel API is to use and what might have to be changed.

**Comment by spacekookie** [comment]
Some initial feedback

- increments feels weird as a method name. t.increments() makes me go "increments what?".
- Having an auto incrementing primary key called id is the overwhelmingly common case. Perhaps it should be the default and something you opt out of, rather than the other way around?
- You should generate 64-bit keys by default. There's no reason to use 32-bit in 2018 (doubly true on PG)
- On PG, there should be no difference between string and text. varchar limits aren't enforced, and actually hurt performance (the perf bit may no longer be true, but it just ends up as text under the hood)

Next, regarding the generics types for Table and Schema, remove those, then change `fn exec(...)` to take a generic backend with `fn exec<T: DatabaseTraits>(&self)`

- Implement `to_string` which does the same as exec now
- Change `exec` to also take a connector backend for convenience?

**Comment by SWW13** [comment]
Add a `Constrain`-Type to build constrains (e.g. unique and possibly primary key) over multiple columns.
Column could use this type to implement it's `unique` feature.

**Comment by rippinrobr** [comment]
is there any thought on adding support for MySQL?

**Comment by spacekookie** [comment]
MySQL is the next backend I want to support

**Comment by rippinrobr** [comment]
I'm currently working on adding MySQL locally, I don't mind sharing it when I'm done if you are interested.

**Comment by spacekookie** [comment]
Absolutely! Even WIP PRs that end up needing to be cleaned up are welcome

**Comment by nicoburns** [comment]
> - Remove increments as a type
> - Implicitly add an auto incrementing primary called "id" for all table

I'd be pretty strongly against this change. Why be opinionated when you don't need to be? Adding a `t.increments()` line to each new table migration is pretty trivial to do if that's the table layout you want. But there are plenty of cases where this isn't what people want. Perhaps they are using GUIDs, or keys from a third party service, and or a composite primary key for a table used for joining two other tables.

**Comment by spacekookie** [comment]
Closing for more specific issues
