### ISSUE TITLE
Track nightly features

### ISSUE THREAD

**Issue by spacekookie** [spacekookie/barrel#10]
There are a few things that are currently in-use that require the nightly compiler. This is a meta issue to track their usage and development. We want to be able to go stable as soon as it's possible

- [ ] [Box syntax](https://github.com/rust-lang/rust/issues/27779) (Not super important but nice)
- [ ] [Clone closures](https://github.com/rust-lang/rust/issues/44490)
- [x] [Custom attributes (for fmt_skip)](https://github.com/rust-lang-nursery/rustfmt#tips) (Resolved with reading docs 😅)

**Comment by ebkalderon** [comment]
Looks like Barrel is extremely close to working on stable Rust.

1. The linked RFC for box syntax and placement new has been recently unaccepted and has been closed. The new tracking issue for box syntax is rust-lang/rust#49733, and its future path to stabilization seems very uncertain and its removal is being considered, AFAICT. As nice as it is, I would recommend that the use of this feature be dropped in favor of achieving stable compiler support. Should it return to the language at a later date in a newer and better form, then feel free to adopt it.
2. [`Clone` closures](https://doc.rust-lang.org/std/clone/trait.Clone.html#closures) appear to have already landed on stable as of Rust 1.26 with the merging of rust-lang/rust#49299. This probably should not require a nightly compiler anymore.
3. Apparently already resolved. 😊

**Comment by spacekookie** [comment]
This issue was resolved with the `v0.2.1` release :tada:
