### ISSUE TITLE
support for custom types/columns

### ISSUE THREAD

**Issue by gabisurita** [spacekookie/barrel#13]
I would like to use the schema migration tool to add some PostgreSQL backend specific types (e.g postgis Point) alongside with a majority of primitive types. I think it would be nice if the Column enum supported a custom type, at least for a while. Thoughts?

**Comment by spacekookie** [comment]
This sounds like a really nice idea and I think I already know a pretty good way of implementing it too. There's some refactoring coming to barrel and I've been thinking about changing the type system for columns entirely too.

I'll take this into consideration but it sounds like something that should be supported, not just for Postgres specific features (although I'm no expert when it comes to databases so I'm not entirely sure what database specific types exist for other databases :stuck_out_tongue_winking_eye:)

Thanks for the feedback :slightly_smiling_face:
