### ISSUE TITLE
Implement SQLite3 backend

### ISSUE THREAD

**Issue by spacekookie** [spacekookie/barrel#16]
Do everything the basic postgres backend does plus whatever database specific features we want, outlined in #15 and #17

**Comment by spacekookie** [comment]
The state of this is that generally it would work, however some features aren't supported by SQlite3 (such as renaming columns/tables) which made for a very awkward user experience.

I hadn't quite figured out what the best way to go about this was (optionally I wanted to let people provide some schema information which would help barrel get around that).

What I can do is publish 0.3.0 soon with the sqlite feature enabled (and not hidden behind `unstable`, then work on any sort of schema processing later. Maybe not the worst idea considering I haven't had a lot of time to work on this recently either.

**Comment by jxs** [comment]
> however some features aren't supported by SQlite3 (such as renaming columns/tables) which made for a very awkward user experience.

yeah, that's an old sqlite caveat, the only way to get around that is to create a new table with the renamed/new column's, move the data onto the new table, and then delete the old one.
If that could be implemented, it would be awesome, although i did not expect that to exist when i looked upon the sqlite backend ehe, maybe a comment above the [unimplemented! macro](https://github.com/spacekookie/barrel/blob/master/src/backend/sqlite3.rs#L68) explaining that it is a sqlite unimplemented feature, and not barrel could help 

> What I can do is publish 0.3.0 soon with the sqlite feature enabled (and not hidden behind unstable, then work on any sort of schema processing later. Maybe not the worst idea considering I haven't had a lot of time to work on this recently either.

that would be great, thanks! :)

**Comment by spacekookie** [comment]
This has been resolved for now. Should have another look at the sqlite module when the new type system is done
