### ISSUE TITLE
Create generic backend connector

### ISSUE THREAD

**Issue by spacekookie** [spacekookie/barrel#2]
Connect up the schema with the Diesel backend but make it easy enough to use a different database connector if one so choses.

**Comment by spacekookie** [comment]
# This issue is partially resolved, but will be moved to a different milestone

Currently this is how a connection is created (Diesel + PGSQL are the only supported options)
```
Connector::<DieselPGSQL>::new(my_db_env_here);
```

This is suboptimal. Much cooler (imo) would be

```
Connector::<Diesel, PGSQL>::new(my_db_env_here);
```

Would this be the same `PGSQL` backend used for the schema generation? Can that just implement the `DbConnection` trait for this purpose? Is that advisable? Lots of open questions 🤷‍♀️

**Comment by jaemk** [comment]
I've been working on a crate ([migrant_lib](https://github.com/jaemk/migrant_lib)) that handles all the backend stuff related to defining and running migrations. It'd be cool if we could join forces here, barrel could handle sql generation and migrant can handle configuration and execution? In this case, barrel could be freely used in [`FnMigration`](https://docs.rs/migrant_lib/0.17.3/migrant_lib/migration/struct.FnMigration.html)s (see [example](https://github.com/jaemk/migrant_lib/blob/master/examples/embedded_programmable.rs))!

**Comment by spacekookie** [comment]
Excellent! At this point barrel will also be integrated with the Diesel migrations toolkit so something generic that can be used from different backends is definitely required.

I'm gonna have a look at your crate in some more detail soon but it looks really cool. And joining forces here would definitely be a good thing 👍

**Comment by spacekookie** [comment]
I think this issue has been resolved. Basically there are two ways to use barrel going from `v0.2.0` onwards:

### Just generate strings

You can just use barrel to get raw SQL strings for a specific database for you. Then you run those via whatever database connection you happen to have

```rust
let mut m = Migration::new();
m.create_table("users", |t| {
  t.add_column("name", Varchar(255)).default("Anonymous");
});
m.exec::<Pg>();
```
This will generate Postgres specific SQL to create table.

### Via  `impl DatabaseExecutor` (name might change)

Just implement this trait on your own database connection and then call `m.execute(&mut runner)` where `runner` is your database type

```rust
impl DatabaseExecutor for CoolSqlConnection {
  fn execute<S: Into<String>>(&mut self, sql: S) {
    // ... handle database logic ...
  }
}
```

This way it's really easy for users to just use barrel in their own stuff while also making it convenient for library developers to integrate barrel into their own types 🎉
