### ISSUE TITLE
docs are broken

### ISSUE THREAD

**Issue by jxs** [spacekookie/barrel#22]
Hi there,
it seems the docs are broken for the [latest version](https://docs.rs/crate/barrel/0.2.5/builds)

**Comment by spacekookie** [comment]
I've been investigating this today and it looks like the Rust version used by `docs.rs` (`2018-06-02`) doesn't build diesel properly, which means the docs (which have code depending on diesel) will fail for this.

The only way to fix this right now would be to add another feature which is only enabled for `docs.rs` builds and gates away a bunch of diesel stuff which means it won't be pulled in as a dependency anymore. But that's incredibly hacky :smirk:

**Comment by joelgallant** [comment]
It looks like this is fixed?

**Comment by jxs** [comment]
yeah seems so, going to close it. Thanks :)
