### ISSUE TITLE
create multiple tables per migration

### ISSUE THREAD

**Issue by jxs** [spacekookie/barrel#23]
currently it's not possible to call multiple `create_table`'s per migration, because `create_table` doesn't check if it there was already any change in `changes`.
Does this feature make sense to you? if so I can try to implement it and PR

**Comment by spacekookie** [comment]
Why would this not already be possible? You can call `create_table` twice which will create two `TableChange` objects for each table you want to create. Or am I misunderstanding your question?

**Comment by jxs** [comment]
sorry, let me try to give better context
```rust
    let mut m = Migration::new();
    m.create_table("artist", |t| {
        t.add_column("name", Type::Text);
        t.add_column("description", Type::Text);
        t.add_column("pic", Type::Text);
        t.add_column("mbid", Type::Text);
    });
    m.create_table("album", |t| {
        t.add_column("name", Type::Text);
        t.add_column("pic", Type::Text);
        t.add_column("mbid", Type::Text);
    });
    println!("{}", m.make::<Sqlite>());
```

prints : 
```sql
CREATE TABLE "artist" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT  , "name" TEXT  , "description" TEXT  , "pic" TEXT  , "mbid" TEXT  )CREATE TABLE "album" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT  , "name" TEXT  , "pic" TEXT  , "mbid" TEXT  )
```

which then returns syntax error: `Error: near "CREATE": syntax error` if i call it rusqlite's `execute_batch` because it's missing the `;` at the end of the first create table 

what i was asking was if create table could either insert `;` at the end of its instruction, or the second create_table check if it was already called, and prepend the `;`

**Comment by spacekookie** [comment]
Hey there! Sorry I'm only now getting back to you – it's been crazy.

Yea that should absolutely be possible. I'll try to fix it soon and push an update :)

**Comment by jxs** [comment]
Hi, no worries :)
awesome! 👍
