### ISSUE TITLE
Re-Adding `increments` or `primary` table functions

### ISSUE THREAD

**Issue by spacekookie** [spacekookie/barrel#49]
It's been raised in #1, #18 that having an implicit `id` key that will correspond to the database main primary key might feel very backwards if someone chooses not to use it or wants a different primary key type (i.e. UUID #21).

I kinda agree with this sentiment, although am open to feedback defending an auto-key. The three choices I see here then are:

- A function `increments()` that simply adds an implicit `id` primary key, like in `barrel 0.1.0`
- A function `primary(_)` which takes a `Type` and assigns it to an implicit `id` column
- Handle primary keys via `add_column("id", _)` like all other columns

I would like to have this issue solved before `0.5.0` is pushed out since I'd also like to commit to some API stability past that point :sweat_smile:

**Comment by rippinrobr** [comment]
I am in favor of flexibility if you want to use your own PK, that's fine. If you want one auto-generated that's great too. As long as it is easy to tell barrel what you want to do, it works for me.

**Comment by spacekookie** [comment]
Yea actually I think just sticking with `add_column("id", types::primary())` is fine for now. I was wondering about `fn primary(tt: Type)` but would people always want to call it `id`? What if the "primary" is actually something completely different. Then we could just call it `fn id(...)`.

But that's too many decisions for now so just making it explicit is probably a good start
